/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.helmo.gbeditor;

class AppTest {
    /*
    @Test void appHasAGreeting() {
        Repository repository=new Repository();
        String path = repository.initPath();
        //assertEquals(path,"C:\\Users\\guill\\ue36\\i210310.json");
        File file=new File(path);
        //assertFalse(file.exists());

        //String isbn="2-210310-10-1";
        //Isbn isbnO=Isbn.fromStringToIsbn(isbn);
        assertTrue("2-210310-10".matches("^[0-9]{1}-[0-9]{6}-[0-9]{2}$"));
    }

     */
}
